[package]
name = "post-action-compute-risk-and-residual"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0.111"
serde = { version = "1.0", features = ["derive"] }

[profile.release]
lto = true