name: Tests

permissions: {}

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tests:
    strategy:
      matrix:
        tuleap_functions:
          - "artifact-post-action/auto-assign"
          - "artifact-post-action/compute-risk"
          - "artifact-post-action/post-action-add-comment"
    runs-on: ubuntu-24.04
    name: Tests (${{ matrix.tuleap_functions }})
    defaults:
      run:
        working-directory: ${{ matrix.tuleap_functions }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: cachix/install-nix-action@ab739621df7a23f52766f9ccc97f38da6b7af14f # v31.10.5
      - name: Prepare
        run: nix-shell --run "make prepare"
      - name: Tests
        run: nix-shell --pure --run "make tests"
      - name: Build
        run: nix-shell --pure --run "make build"
  formatting_linting:
    name: Check for formatting or linting issues
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: cachix/install-nix-action@ab739621df7a23f52766f9ccc97f38da6b7af14f # v31.10.5
      - name: Build
        run: nix-shell --pure --run 'treefmt --ci'
